import * as stylex from "@stylexjs/stylex";

import { siteTokens } from "../SiteTheme.stylex";

export const walkthroughStyles = stylex.create({
  sidecarList: { borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: siteTokens.border },
  sidecarItem: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: siteTokens.border,
  },
  sidecarButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    minHeight: 58,
    padding: "14px 0",
    textAlign: "left",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "none",
    color: siteTokens.muted,
    fontFamily: "inherit",
    fontSize: 16,
    fontWeight: 550,
    letterSpacing: "-.02em",
    transition: "color 150ms ease-out",
    ":hover": { color: siteTokens.text },
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: siteTokens.muted,
      outlineOffset: 4,
    },
  },
  selectedText: { color: siteTokens.text },
  sidecarDetail: { display: "flex", flexDirection: "column", gap: 18, paddingBottom: 22 },
  instant: { transition: "none" },
  chevronMotion: {
    transition: "transform 240ms cubic-bezier(0.25, 1, 0.5, 1)",
    "@media (prefers-reduced-motion: reduce)": { transition: "none" },
  },
  chevron: { flexShrink: 0, transform: "rotate(-90deg)", color: siteTokens.muted },
  chevronOpen: { transform: "rotate(0deg)" },
  copy: { color: siteTokens.muted, fontSize: 14, lineHeight: 1.65, margin: 0, maxWidth: "48ch" },
  media: { maxWidth: 1280, minWidth: 0 },
  videoFrame: {
    backgroundColor: siteTokens.surface,
    borderColor: siteTokens.border,
    borderRadius: 10,
    borderStyle: "solid",
    borderWidth: 1,
    overflow: "hidden",
  },
  video: { aspectRatio: "16 / 9", display: "block", objectFit: "contain", width: "100%" },
  mobileVideo: { aspectRatio: "1 / 1" },
  mobileMedia: { maxWidth: 768 },
  mediaControls: {
    alignItems: "center",
    display: "flex",
    gap: 12,
    justifyContent: "flex-end",
    minHeight: 48,
  },
  mediaButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: siteTokens.muted,
    display: "inline-flex",
    fontFamily: "inherit",
    fontSize: 11,
    gap: 7,
    justifyContent: "center",
    lineHeight: 1,
    minHeight: 44,
    minWidth: 44,
    padding: "8px 4px",
    transition: "color 150ms ease-out, transform 150ms ease-out",
    ":active": { transform: "scale(.96)" },
    ":focus-visible": {
      outlineColor: siteTokens.muted,
      outlineOffset: 2,
      outlineStyle: "solid",
      outlineWidth: 2,
    },
    ":hover": { color: siteTokens.text },
    "@media (prefers-reduced-motion: reduce)": {
      transition: "none",
      ":active": { transform: "none" },
    },
  },
  mediaError: { color: siteTokens.muted, fontSize: 12, marginRight: "auto" },
  dialog: {
    backgroundColor: siteTokens.background,
    borderColor: siteTokens.border,
    borderRadius: 12,
    borderStyle: "solid",
    borderWidth: 1,
    color: siteTokens.text,
    maxHeight: "94dvh",
    maxWidth: "none",
    padding: 20,
    width: "min(1400px, 96vw)",
    "::backdrop": { backgroundColor: "rgb(0 0 0 / .8)" },
  },
  dialogHeader: { alignItems: "center", display: "flex", gap: 20, justifyContent: "space-between" },
  dialogTitle: { fontSize: 22, fontWeight: 550, letterSpacing: "-.03em", margin: 0 },
  dialogHint: { color: siteTokens.muted, fontSize: 12, lineHeight: 1.6, margin: "8px 0 20px" },
  expandedScroll: { overflow: "auto" },
  expandedVideo: { display: "block", minWidth: 900, width: "100%" },
});
